# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'SkyWellTestApp' do
pod 'AFNetworking'
pod 'MagicalRecord'
end

target 'SkyWellTestAppTests' do
end

target 'SkyWellTestAppUITests' do

end

